### PR TITLE
Add some aliases for alternate spellings

### PR DESCRIPTION
**Pull request by meew0**

### CODE REVIEW

**Comment by RX14** [comment]
We could have a compile-time flag to turn these off :P

**Comment by RX14** [comment]
He actually did it the absolute madman.

**Comment by RX14** [comment]
Ok, I think we need to think about our stance on this issue more carefully. There are many different methods on the raw objects that we could "crystalize", for example adding `?` to query-ish methods. Should we also explore adding simple query methods such as this?
```cr
def guild?
  !@guild_id.nil?
end
```

The question is where we draw the line between being helpful and being low-level. All of these things I've suggested add no runtime cost.

**Comment by meew0** [comment]
I agree that this should be considered, however it seems out of the scope of this PR. This PR is just intended to decrease confusion, these other suggestions would be for utility.

**Comment by RX14** [comment]
Yeah, let's just squash and merge this.

**Pull request merged**
