### PR TITLE
Add missing Channel fields

### PR DESCRIPTION
**Pull request by zatherz**
https://discordapp.com/developers/docs/resources/channel#channel-object-channel-structure

### CODE REVIEW

**Comment by RX14** [comment]
Learn to use git.

**Comment by RX14** [comment]
I apologised to @zatherz for being a dipshit. Github :b:roke

**Comment by z64** [comment]
Can you also add `nsfw`? This needs to be added to `REST#modify_channel` too. I had this in a branch but you may as well add it in this PR.

**Comment by zatherz** [comment]
Added.

**Comment by z64** [comment]
Thanks! :)

**Pull request merged**
