### PR TITLE
Add missing channel fields

### PR DESCRIPTION
**Pull request by zatherz**
https://discordapp.com/developers/docs/resources/channel#channel-object-channel-structure

### CODE REVIEW

**Comment by zatherz** [comment]
Sorry. Made a mistake while branching.

**Comment by RX14** [comment]
Then fix it properly, don't open a new PR.

**Comment by RX14** [comment]
It's literally a PR *from the same branch* which means creating a new PR was entirely unnecesary.

**Comment by zatherz** [comment]
I remade the branch and GitHub does not allow me to reopen. Please learn basic communication skills.

**Comment by RX14** [comment]
Na

**Comment by zatherz** [comment]
Your choice

**Pull request closed without merging**
