### PR TITLE
Implement renaming of Time#epoch to #to_unix

### PR DESCRIPTION
**Pull request by greenbigfrog**
~~Wait for crystal 0.27.0 to merge~~
Since crystal 0.27.0 has been released, this can be merged now.

### CODE REVIEW

**Comment by RX14** [comment]
no?

**Comment by kirbyfan64** [comment]
Is there a reason this hasn't been merged yet?

**Comment by Jens0512** [comment]
It seems there are quite a lot of eager people waiting for this merge :D

**Comment by greenbigfrog** [comment]
In the meantime you can simply specify this PR/fork & branch in your `shard.yml` like the following:
```
dependencies:
  discordcr:
    github: greenbigfrog/discordcr
    branch: new-cr
```

**Comment by kirbyfan64** [comment]
@greenbigfrog Yup, that's what I did!

**Comment by vendethiel** [comment]
Could you please tag a new version?

**Comment by r00ster91** [comment]
@vendethiel you can just use the `master` branch so put this in your `shards.yml`:
```yaml
dependencies:
  discordcr:
    github: meew0/discordcr
    branch: master
```

**Comment by vendethiel** [comment]
I'm using a commit tag instead, but yeah sure. I'd still prefer a release to be cut.

**Pull request merged**
